name: CI/CD Express

env:
  ECR_REPO: telemetry-app
  AWS_REGION: eu-west-1
  DYNAMODB_TABLE: telemetry-staging-temperature-readings-aggregation

on:
  workflow_dispatch:

jobs:     
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      telemetry_app_image: ${{ steps.image-build.outputs.telemetry_app_image }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - uses: actions/checkout@v2

    - name: Build, tag, and push image to Amazon ECR
      id: image-build
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPO }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest
        docker push $ECR_REPOSITORY:latest
        echo "::set-output name=telemetry_app_image::$ECR_REPOSITORY:$IMAGE_TAG"
        
        
  staging_plan:
    needs: build_and_push
    defaults:
        run:
          working-directory: ./deploy
    runs-on: ubuntu-latest
    env:
      TF_VAR_telemetry_app_image: ${{needs.build_and_push.outputs.telemetry_app_image}}
    steps:
      - uses: actions/checkout@v2

      - run: echo TF_VAR_telemetry_app_image
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
    
      - uses: hashicorp/setup-terraform@v1.2.1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Workspace Select or Create
        run: terraform workspace select staging || terraform workspace new staging
        
      - name: Terraform Plan
        run: terraform plan
        
        
  staging_apply:
    needs: staging_plan
    defaults:
        run:
          working-directory: ./deploy
    runs-on: ubuntu-latest
    env:
      TF_VAR_telemetry_app_image: ${{needs.build_and_push.outputs.telemetry_app_image}}
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - uses: hashicorp/setup-terraform@v1.2.1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Workspace Select
        run: terraform workspace select staging

      - name: Export ECR Image Full API variable
        run: export TF_VAR_telemetry_app_image=128363080680.dkr.ecr.eu-west-1.amazonaws.com/telemetry-app:d7b59031e09688774e0bcb86454c49c23361c351
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
        
  dynamodb_seed:
    needs: staging_apply
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        
      - name: Install AWS CLI
        run: | 
          sudo apt-get install python3-pip
          pip install awscli --upgrade
        
      - name: Conditional Put-Item API Call to DynamoDB
        run: | 
          sudo apt-get install python3-pip
          pip install awscli --upgrade
          aws dynamodb put-item \
          --table-name ${{ env.DYNAMODB_TABLE }} \
          --item file://deploy/templates/dynamodb/seed.json \
          --condition-expression "attribute_not_exists(total_readings_count)" \
          || true
