name: Destroy Prod

env:
  ECR_REPO: telemetry-app
  AWS_REGION: eu-west-1

on: 
  workflow_dispatch:
  
jobs:
  prod_destroy:
    defaults:
        run:
          working-directory: ./terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v1.2.1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Workspace Select
        run: terraform workspace select prod
        
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
